[package]
name = "cargo-spellcheck"
version = "0.0.1"
authors = ["Bernhard Schuster <bernhard@ahoi.io>"]
edition = "2018"
repository = "https://github.com/drahnr/cargo-spellcheck.git"
homepage = "https://github.com/drahnr/cargo-spellcheck"
license = "MIT OR Apache-2.0"
keywords = ["spellcheck","spelling","grammar"]
description = "Checks all doc comments for spelling mistakes"

[dependencies]
docopt = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
proc-macro2 = { version = "1", features = ["span-locations"] }
walkdir = "2"
syn = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.7"
console = "0.11"
indexmap = "1"

# dictionary
hunspell = { version = "0.1", package = "hunspell-rs" }
# full grammar check
languagetool = "0.1"

